---
- name: dingen 
  hosts: localhost
  gather_facts: no

  vars:
          # {
          #     "runtimes": {
          #         "nvidia": {
          #             "path": "nvidia-container-runtime",
          #             "runtimeArgs": []
          #         }
          #     }
          # }
  tasks:
  - name: load var from file
    slurp:
      src: daemon.json
    register: imported_var
  
  - debug: 
     msg: "{{ imported_var.content|b64decode|from_json }}"

  - name: append more key/values
    set_fact:
            imported_var: "{{ imported_var.content|b64decode|from_json | default([]) | combine({ 'default-runtime': 'nvidia','runtimes': {'nvidia': {'path': 'nvidia-container-runtime', 'runtimeArgs': [] } }}) }}"

  - debug:
      var: imported_var

  - name: write var to file
    copy: 
      content: "{{ imported_var | to_nice_json }}" 
      dest: /root/final.json
